name: CMake

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths: ["códigos/**"]

env:
  BUILD_TYPE: Release

jobs:
  testar-codigos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências principais
        run: |
          sudo apt update
          sudo apt install libvulkan-dev vulkan-validationlayers-dev spirv-tools libglfw3-dev libglm-dev

      - name: Instalar GLSLC
        run: |
          wget https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_clang_release/380/20220202-124409/install.tgz
          tar -xf install.tgz install/bin/glslc
          sudo mv install/bin/glslc /usr/local/bin

      - name: Executar utilidade de teste
        run: ${{github.workspace}}/utilidades.sh t
