name: Integração continua dos códigos

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths: ["códigos/**"]

env:
  BUILD_TYPE: Release

jobs:
  obter-alvos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        
      - name: Obter arquivos modificados
        id: listar-arquivos-modificados
        if: ${{github.event_name == "push"}}
        uses: tj-actions/changed-files@v17
        with:
          path: ${{github.workspace}}/códigos
          separator: ","
      
      - name: Listar todos os diretórios em códigos
        id: listar-diretorios
        if: ${{github.event_name == "workflow_dispatch"}}
        working-directory: ${{github.workspace}}/códigos
        run: |
          python <<EOF
          import json
          import os
          
          subdirs=os.scandir()
          dirs=filter(lambda subdir : subdir.is_dir(), subdirs)
          dirnames=map(lambda dir: dir.name, dirs)
          txt_fmt='::set-output name=dirs::{dirs}'
          print(txt_fmt.format(dirs = json.dumps(list(dirnames))))
          EOF
        
      - name: Filtrar entrada para alvos
        id: filtrar-alvos
        run: |
          python <<EOF
          txt_fmt='::set-output name=alvos::{alvos}'
          if ${{github.event_name == "push"}}:
            arquivos_adicionados=${{steps.listar-arquivos-modificados.outputs.added_files}}.split(',')
            arquivos_modificados=${{steps.listar-arquivos-modificados.outputs.modified_files}}.split(',')
            arquivos=arquivos_adicionados+arquivos_modificados
            alvos=list(set(map(lambda a: a.split('/')[0], alvos)))
            
            import json
            print(txt_fmt.format(alvos = json.dumps(alvos)))
            
          elif ${{github.event_name == "workflow_dispatch"}}:
            txt_json=${{steps.listar-diretorios.outputs.dirs}}
            print(txt_fmt.format(alvos = txt_json))
          EOF
    
    outputs:
      alvos: ${{steps.filtrar-alvos.outputs.alvos}}

  testar-alvos:
    needs: obter-alvos
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        alvo: ${{fromJSON(needs.listar-alvos.outputs.alvos)}}

    steps:
      - uses: actions/checkout@v2

      - name: Instalar SDK da Vulkan
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.204-focal.list https://packages.lunarg.com/vulkan/1.3.204/lunarg-vulkan-1.3.204-focal.list
          sudo apt update
          sudo apt install vulkan-sdk

      - name: Instalar outras dependências
        run: |
          sudo apt update
          sudo apt install libglfw3-dev libglm-dev
       
      - name: Fazer cache do GLSLC
        id: cache-glslc
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/glslc
          key: glslc

      - name: Instalar GLSLC
        if: steps.cache-glslc.outputs.cache-hit != true
        run: |
          wget --quiet https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_clang_release/380/20220202-124409/install.tgz
          tar -xf install.tgz install/bin/glslc
          sudo mv install/bin/glslc /usr/local/bin

      - name: Configurar projeto
        working-directory: ${{github.workspace}}/códigos/${{matrix.alvo}}
        run: cmake -B build
        
      - name: Montar projeto
        working-directory: ${{github.workspace}}/códigos/${{matrix.alvo}}
        run: cmake --build build
